### ISSUE TITLE
Is this just a scam?

### ISSUE THREAD

**Issue by David-crypto1** [bscWallet/BSCWallet#2]
Is this a scam? You have taken my entire crypto portfolio and left me unable to transfer out??

**Comment by dylanb1001993** [comment]
yes it is !!! the same has happened with me!!

**Comment by David-crypto1** [comment]
I sorted this now, it doesn’t recognise anything but BSC but if you setup another wallet using the secret phrase then they all transfer back

**Comment by dylanb1001993** [comment]
ahhh!!’ sorry, how do i do it ?! omg you are a life saver !!

how do i get my secret phrase? cos it asks for a password and i dont have
one?!

**Comment by David-crypto1** [comment]
Give me an hour or so, I’m just in the middle of something. I’ll try to remember what I did and send it over to you, I’m sure it’s not to difficult

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by David-crypto1** [comment]
As I recall…..
1. Log into the app BSCwallet
2. Find your secret phrase or code
3. Setup a new wallet, I used trust wallet
4. When trust/wallet asks if you have an existing wallet say yes
5. It will ask if it’s a multi coin wallet yes/no
6. Once you say yes it asks for the secret phrase or code
7. Enter the code and your wallet will become live
8. Last of all, add all of the token names that you have into the wallet and the coins will automatically populate in the wallet

I hope that all works out for you as it did me 👍🏻

**Comment by dylanb1001993** [comment]
Awesome, thanks!
